/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package matrix.lib;

import org.junit.*;

import static org.junit.Assert.*;

public class MatrixFloatTest {

    @Test
    public void TestMatrixMultiplication() {
        /*
        Matrix B
        2 7 5 8 4
        5 0 5 2 5
        6 7 9 8 7
        8 5 0 1 6
        7 9 2 6 4
        Matrix B
        2 2 0 3 4
        0 0 0 2 0
        1 2 4 3 2
        3 0 0 1 1
        2 4 2 1 4
        Matrix C
        41 30 28 47 42
        31 40 30 37 52
        59 58 50 74 78
        31 40 12 41 57
        42 34 16 55 54
        */
        int size = 5;
        MatrixFloat matrix_a = new MatrixFloat(size);
        MatrixFloat matrix_b = new MatrixFloat(size);
        MatrixFloat matrix_expected = new MatrixFloat(size);

        // TODO Update values to be correct
        float[] matrix_a_data = {2.35f, 7.25f, 5.78f, 8.0f, 4.0f, 5.0f, 0.0f, 5.0f, 2.0f, 5.0f, 6.0f, 7.0f, 9.0f, 8.0f, 7.0f, 8.0f, 5.0f, 0.0f, 1.0f, 6.0f, 7.0f, 9.0f, 2.0f, 6.0f, 4.0f};
        float[] matrix_b_data = {2.45f, 2.54f, 0.54f, 3.0f, 4.0f, 0.0f, 0.0f, 0.0f, 2.0f, 0.0f, 1.0f, 2.0f, 4.0f, 3.0f, 2.0f, 3.0f, 0.0f, 0.0f, 1.0f, 1.0f, 2.0f, 4.0f, 2.0f, 1.0f, 4.0f};
        float[] matrix_expected_data =
                {41.0f, 30.0f, 28.0f, 47.0f, 42.0f, 31.0f, 40.0f, 30.0f, 37.0f, 52.0f, 59.0f, 58.0f, 50.0f, 74.0f, 78.0f, 31.0f, 40.0f, 12.0f, 41.0f, 57.0f, 42.0f, 34.0f, 16.0f, 55.0f, 54.0f};

        try {
            matrix_a.set(matrix_a_data);
            matrix_b.set(matrix_b_data);
            matrix_expected.set(matrix_expected_data);
        } catch (Exception ex) {
            fail();
        }
        TimeController time = new TimeController();

        AMatrix matrix_computed = matrix_a.multiply(matrix_b);

        // assert statements
        assertEquals(
                "Result of matrix multiplication must be equal to expected matrix",
                matrix_expected, matrix_computed
        );
    }
}
