name: Java CI

on: [push]

jobs:
  build:
    name: Assemble lib
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Initialize grade
      run: ./gradlew wrapper
    - name: Assemble with Gradle with debug symbols
      run: ./gradlew assembleDebug
    - name: Assemble with Gradle w/o debug symbols
      run: ./gradlew assembleRelease
