name: Java CI

on: [push]

jobs:
  build:
    name: Assemble lib
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1.1.0
      with:
        java-version: 1.8
    - name: What Java?
      run: java -version
    - name: Initialize grade
      run: ./gradlew
    - name: Assemble with debug symbols
      run: ./gradlew assembleDebug
    - name: Assemble w/o debug symbols
      run: ./gradlew assembleRelease
